version: 2
updates:
    -
        package-ecosystem: "npm"
        directory: "/"
        open-pull-requests-limit: 3
        target-branch: "master"
        schedule:
            interval: "monthly"
        allow:
            - dependency-type: "production"
        commit-message:
            prefix: "fix"
            prefix-development: "chore"
            include: "scope"
        pull-request-branch-name:
            separator: "-"
